### ISSUE TITLE
Handle gitian builder

### ISSUE THREAD

**Issue by cornelius** [dtr-org/unit-e-clonemachine#24]
The gitian builder consists of the script `contrib/gitian-build.py` and some related files such as the gitian descriptors, the list of keys of people who build and provide signatures, as well as some documentation. We have changed all this quite heavily so we should make sure that clonemachine handles it correctly by marking the files we deleted and we took over.

This is the list of files to be handled:

```yaml
appropriated_files:
- contrib/gitian-build.py
- contrib/gitian-keys/keys.txt
- doc/gitian-building.md

removed_files:
- contrib/gitian-descriptors/gitian-osx-signer.yml
```

The other gitian descriptors are still close to the upstream version and we do want to merge changes so we let git handle them.
